platform :ios, '15.0'

source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'TikiClient_Example' do
    pod 'TikiClient', :path => '../'
  end
    
  target 'TikiClientExampleTests' do
    pod 'TikiClient', :path => '../'
  end