# Reference: https://github.com/repository-settings/app

_extends: .github

repository:
  name: client-library-ios
  description: integrate your iOS app with mytiki.com
  homepage: https://docs.mytiki.com/reference/client-library-overview
  topics: iOS, library
  private: false
  has_projects: true
  has_discussions: false
  has_issues: true

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage
  - name: frontend
    permission: push

environments:
  - name: production

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - test
          - Analyze (swift)

milestones:
  - title: 0.2.0
    description: |
      Adds support for intelligent email scraping of e-receipts. Emails are fetched using a pre-qualified list
      of known receipt senders and parsed locally to the mobile device to protect privacy. Emails are eagerly fetched
      starting with the most recent and working progressively in reverse chronological order when time-permitted.
    state: open

  - title: 0.3.0
    description: |
      Implements the services for "Improve OptIn rates" feature. The Improve OptIn feature provides a structured approach 
      to create compelling ffers, present them to users, and manage user decisions efficiently.
    state: closed

  - title: 0.4.0
    description: |
      Implements the UIs for "Improve OptIn rates" feature. Adds pre-built UIs that can be customized to match the app's visual identity.
    state: closed

  - title: 0.5.0
    description: |
      Adds functionalities to "Improve OptIn rates" and matches Android Client Lib releases.
    state: open