{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerControllerDidCancel(_:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/start(onFinish:)"]}],"sections":[],"variants":[{"paths":["\/documentation\/tikiclient\/capturescan"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tikiclient\/capturescan"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSCoding","doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSObject","doc:\/\/org.cocoapods.TikiClient\/s7CVarArgP","doc:\/\/org.cocoapods.TikiClient\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.TikiClient\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.TikiClient\/SQ","doc:\/\/org.cocoapods.TikiClient\/SH","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIImagePickerControllerDelegate","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UINavigationControllerDelegate","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.TikiClient\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient"]]},"metadata":{"roleHeading":"Class","modules":[{"name":"TikiClient"}],"role":"symbol","externalID":"c:@M@TikiClient@objc(cs)CaptureScan","title":"CaptureScan","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureScan"}],"navigatorTitle":[{"text":"CaptureScan","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CaptureScan","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.TikiClient/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSCoding"},"doc://org.cocoapods.TikiClient/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan/imagePickerController(_:didFinishPickingMediaWithInfo:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imagePickerController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didFinishPickingMediaWithInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController","text":"UIImagePickerController"},{"kind":"text","text":"."},{"text":"InfoKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerController(_:didFinishPickingMediaWithInfo:)","title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","navigatorTitle":[{"text":"imagePickerController:didFinishPickingMediaWithInfo:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/tikiclient\/capturescan\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"},"doc://org.cocoapods.TikiClient/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIContentContainer"},"doc://org.cocoapods.TikiClient/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.TikiClient/objc(pl)UINavigationControllerDelegate":{"type":"unresolvable","title":"UINavigationControllerDelegate","identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UINavigationControllerDelegate"},"doc://org.cocoapods.TikiClient/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.TikiClient/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.TikiClient/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.TikiClient/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.TikiClient/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.TikiClient/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.TikiClient/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.TikiClient/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan/start(onFinish:)":{"abstract":[{"type":"text","text":"Captures an image of a receipt for processing."}],"type":"topic","url":"\/documentation\/tikiclient\/capturescan\/start(onfinish:)","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/start(onFinish:)","kind":"symbol","role":"symbol","title":"start(onFinish:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onFinish"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://org.cocoapods.TikiClient/SH":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.TikiClient/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan/initWithNibName:bundle:":{"abstract":[],"url":"\/documentation\/tikiclient\/capturescan\/initwithnibname:bundle:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNibName:bundle:"}],"type":"topic","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"title":"initWithNibName:bundle:","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/initWithNibName:bundle:","kind":"symbol"},"doc://org.cocoapods.TikiClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.TikiClient\/SQ"},"doc://org.cocoapods.TikiClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.TikiClient\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.TikiClient/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(cs)UIViewController"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan/initWithCoder:":{"abstract":[],"url":"\/documentation\/tikiclient\/capturescan\/initwithcoder:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/initWithCoder:","kind":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","title":"TikiClient","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/tikiclient","type":"topic"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan/imagePickerControllerDidCancel(_:)":{"role":"symbol","navigatorTitle":[{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"title":"imagePickerControllerDidCancel(_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerControllerDidCancel"},{"kind":"text","text":"("},{"text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/tikiclient\/capturescan\/imagepickercontrollerdidcancel(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerControllerDidCancel(_:)"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan":{"kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureScan"}],"type":"topic","navigatorTitle":[{"text":"CaptureScan","kind":"identifier"}],"role":"symbol","title":"CaptureScan","url":"\/documentation\/tikiclient\/capturescan","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan"},"doc://org.cocoapods.TikiClient/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.TikiClient/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.TikiClient/objc(pl)UIImagePickerControllerDelegate":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIImagePickerControllerDelegate","type":"unresolvable","title":"UIImagePickerControllerDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"CaptureScan"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"CaptureScan","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CaptureScan"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerControllerDidCancel(_:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/initWithCoder:","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/initWithNibName:bundle:"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(cs)UIViewController"],"kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(pl)UIImagePickerControllerDelegate","doc:\/\/org.cocoapods.TikiClient\/objc(pl)UINavigationControllerDelegate"],"kind":"relationships","type":"conformsTo"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"CaptureScan","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}]}]}},{"value":"imagePickerController:didFinishPickingMediaWithInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/fragments"},{"value":"imagePickerControllerDidCancel:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan~1imagePickerControllerDidCancel(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan~1imagePickerControllerDidCancel(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan\/title","value":"CaptureScan","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan\/fragments","value":[{"text":"CaptureScan","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}