{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"symbolKind":"class","role":"symbol","roleHeading":"Class","title":"CryptoExportImportManager","modules":[{"name":"TikiClient"}],"navigatorTitle":[{"kind":"identifier","text":"CryptoExportImportManager"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CryptoExportImportManager","kind":"identifier"}],"externalID":"c:@M@TikiClient@objc(cs)CryptoExportImportManager"},"variants":[{"paths":["\/documentation\/tikiclient\/cryptoexportimportmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tikiclient\/cryptoexportimportmanager"]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/PEMKeyFromDERKey(_:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/bytesNeededForRepresentingInteger(_:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/encodeASN1LengthParameter(_:buffer:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportECPublicKeyToDER(_:keyType:keySize:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportECPublicKeyToPEM(_:keyType:keySize:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportPublicKeyToDER(_:keyType:keySize:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportPublicKeyToPEM(_:keySize:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportRSAPublicKeyToDER(_:keyType:keySize:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportRSAPublicKeyToPEM(_:keyType:keySize:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/importPublicKeyReferenceFromDERCertificate(_:)"],"title":"Instance Methods"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSObject","doc:\/\/org.cocoapods.TikiClient\/s7CVarArgP","doc:\/\/org.cocoapods.TikiClient\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.TikiClient\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.TikiClient\/SQ","doc:\/\/org.cocoapods.TikiClient\/SH"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient"]]},"kind":"symbol","abstract":[{"text":"This class exists due to the easy and intuitive way of using public keys generated outside iOS in","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the Security framework and CommonCrypto tools (yes, I’m being sarcastic here)."},{"type":"text","text":" "},{"type":"text","text":"CryptoCertificateImportManager is in charge of importing a certificate and obtaining a valid key"},{"type":"text","text":" "},{"text":"reference to use in any of SecKey operations (SecKeyEncrypt, SecKeyRawVerify…).","type":"text"},{"text":" ","type":"text"},{"text":"As far as I know, any other way of importing and using public keys from the outside is not","type":"text"},{"type":"text","text":" "},{"text":"advised: https:\/\/devforums.apple.com\/message\/301532#301532","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CryptoExportImportManager","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/exportRSAPublicKeyToDER(_:keyType:keySize:)":{"url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/exportrsapublickeytoder(_:keytype:keysize:)","abstract":[{"type":"text","text":"This function prepares a RSA public key generated with Apple SecKeyGeneratePair to be exported"},{"type":"text","text":" "},{"text":"and used outisde iOS, be it openSSL, PHP, Perl, whatever. By default Apple exports RSA public","type":"text"},{"type":"text","text":" "},{"text":"keys in a very raw format. If we want to use it on OpenSSL, PHP or almost anywhere outside iOS, we","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"need to remove add the full PKCS#1 ASN.1 wrapping. Returns a DER representation of the key."}],"title":"exportRSAPublicKeyToDER(_:keyType:keySize:)","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportRSAPublicKeyToDER(_:keyType:keySize:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exportRSAPublicKeyToDER","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"keyType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"keySize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.TikiClient/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.TikiClient\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.TikiClient/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.TikiClient\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/exportECPublicKeyToPEM(_:keyType:keySize:)":{"kind":"symbol","title":"exportECPublicKeyToPEM(_:keyType:keySize:)","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/exportecpublickeytopem(_:keytype:keysize:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exportECPublicKeyToPEM","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"keySize"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportECPublicKeyToPEM(_:keyType:keySize:)","abstract":[{"text":"This function prepares a EC public key generated with Apple SecKeyGeneratePair to be exported","type":"text"},{"type":"text","text":" "},{"text":"and used outisde iOS, be it openSSL, PHP, Perl, whatever. It basically adds the proper ASN.1","type":"text"},{"type":"text","text":" "},{"type":"text","text":"header and codifies the result as valid base64 string, 64 characters split."},{"text":" ","type":"text"},{"type":"text","text":"Returns a DER representation of the key."}]},"doc://org.cocoapods.TikiClient/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/PEMKeyFromDERKey(_:)":{"kind":"symbol","title":"PEMKeyFromDERKey(_:)","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/pemkeyfromderkey(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PEMKeyFromDERKey","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/PEMKeyFromDERKey(_:)","abstract":[{"type":"text","text":"This method transforms a DER encoded key to PEM format. It gets a Base64 representation of"},{"text":" ","type":"text"},{"type":"text","text":"the key and then splits this base64 string in 64 character chunks. Then it wraps it in"},{"type":"text","text":" "},{"text":"BEGIN and END key tags.","type":"text"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/exportECPublicKeyToDER(_:keyType:keySize:)":{"url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/exportecpublickeytoder(_:keytype:keysize:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportECPublicKeyToDER(_:keyType:keySize:)","title":"exportECPublicKeyToDER(_:keyType:keySize:)","abstract":[{"type":"text","text":"This function prepares a EC public key generated with Apple SecKeyGeneratePair to be exported"},{"type":"text","text":" "},{"type":"text","text":"and used outisde iOS, be it openSSL, PHP, Perl, whatever. It basically adds the proper ASN.1"},{"type":"text","text":" "},{"text":"header and codifies the result as valid base64 string, 64 characters split.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Returns a DER representation of the key."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exportECPublicKeyToDER","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"keyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"keySize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}]},"doc://org.cocoapods.TikiClient/SQ":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/exportPublicKeyToPEM(_:keySize:)":{"kind":"symbol","title":"exportPublicKeyToPEM(_:keySize:)","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/exportpublickeytopem(_:keysize:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exportPublicKeyToPEM"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"keySize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportPublicKeyToPEM(_:keySize:)","abstract":[{"text":"Exports a key retrieved from the keychain so it can be used outside iOS (i.e: in OpenSSL).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Returns a PEM representation of the key."}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/importPublicKeyReferenceFromDERCertificate(_:)":{"kind":"symbol","title":"importPublicKeyReferenceFromDERCertificate(_:)","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/importpublickeyreferencefromdercertificate(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"importPublicKeyReferenceFromDERCertificate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") -> ","kind":"text"},{"text":"SecKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/importPublicKeyReferenceFromDERCertificate(_:)","abstract":[{"type":"text","text":"Extracts the public key from a X.509 certificate and returns a valid SecKeyRef that can be"},{"type":"text","text":" "},{"text":"used in any of SecKey operations (SecKeyEncrypt, SecKeyRawVerify…).","type":"text"},{"text":" ","type":"text"},{"text":"Receives the certificate data in DER format.","type":"text"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/exportPublicKeyToDER(_:keyType:keySize:)":{"kind":"symbol","title":"exportPublicKeyToDER(_:keyType:keySize:)","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/exportpublickeytoder(_:keytype:keysize:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"exportPublicKeyToDER","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"text":"keyType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keySize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportPublicKeyToDER(_:keyType:keySize:)","abstract":[{"type":"text","text":"Exports a key retrieved from the keychain so it can be used outside iOS (i.e: in OpenSSL)."},{"type":"text","text":" "},{"type":"text","text":"Returns a DER representation of the key."}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager":{"url":"\/documentation\/tikiclient\/cryptoexportimportmanager","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CryptoExportImportManager"}],"title":"CryptoExportImportManager","abstract":[{"text":"This class exists due to the easy and intuitive way of using public keys generated outside iOS in","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the Security framework and CommonCrypto tools (yes, I’m being sarcastic here)."},{"type":"text","text":" "},{"type":"text","text":"CryptoCertificateImportManager is in charge of importing a certificate and obtaining a valid key"},{"type":"text","text":" "},{"type":"text","text":"reference to use in any of SecKey operations (SecKeyEncrypt, SecKeyRawVerify…)."},{"type":"text","text":" "},{"type":"text","text":"As far as I know, any other way of importing and using public keys from the outside is not"},{"type":"text","text":" "},{"text":"advised: https:\/\/devforums.apple.com\/message\/301532#301532","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CryptoExportImportManager","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.TikiClient/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.TikiClient/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/encodeASN1LengthParameter(_:buffer:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/encodeASN1LengthParameter(_:buffer:)","title":"encodeASN1LengthParameter(_:buffer:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encodeASN1LengthParameter"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"buffer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/encodeasn1lengthparameter(_:buffer:)","abstract":[{"text":"Generates an ASN.1 length sequence for the given length. Modifies the buffer parameter by","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"writing the ASN.1 sequence. The memory of buffer must be initialized (i.e: from an NSData)."},{"type":"text","text":" "},{"type":"text","text":"Returns the number of bytes used to write the sequence."}],"kind":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/exportRSAPublicKeyToPEM(_:keyType:keySize:)":{"kind":"symbol","title":"exportRSAPublicKeyToPEM(_:keyType:keySize:)","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/exportrsapublickeytopem(_:keytype:keysize:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exportRSAPublicKeyToPEM","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keyType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"keySize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/exportRSAPublicKeyToPEM(_:keyType:keySize:)","abstract":[{"text":"This function prepares a RSA public key generated with Apple SecKeyGeneratePair to be exported","type":"text"},{"text":" ","type":"text"},{"text":"and used outisde iOS, be it openSSL, PHP, Perl, whatever. By default Apple exports RSA public","type":"text"},{"type":"text","text":" "},{"type":"text","text":"keys in a very raw format. If we want to use it on OpenSSL, PHP or almost anywhere outside iOS, we"},{"type":"text","text":" "},{"text":"need to remove add the full PKCS#1 ASN.1 wrapping. Returns a DER representation of the key.","type":"text"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/init":{"kind":"symbol","title":"init","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/init","abstract":[]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager/bytesNeededForRepresentingInteger(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesNeededForRepresentingInteger"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[{"type":"text","text":"Returns the number of bytes needed to represent an integer."}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/bytesNeededForRepresentingInteger(_:)","type":"topic","url":"\/documentation\/tikiclient\/cryptoexportimportmanager\/bytesneededforrepresentinginteger(_:)","kind":"symbol","title":"bytesNeededForRepresentingInteger(_:)","role":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","title":"TikiClient","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/tikiclient","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"CryptoExportImportManager"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CryptoExportImportManager","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CryptoExportImportManager","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager\/init"]}],"op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"CryptoExportImportManager","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"CryptoExportImportManager","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CryptoExportImportManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CryptoExportImportManager\/fragments","value":[{"kind":"identifier","text":"CryptoExportImportManager"}],"op":"replace"}]}]}