{"identifier":{"url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/authorizationStatus","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didFailWithError:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didUpdateLocations:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManagerDidChangeAuthorization(_:)"]},{"identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/ObservableObject-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tikiclient\/locationdatamanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tikiclient\/locationdatamanager"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.TikiClient\/7Combine16ObservableObjectP","doc:\/\/org.cocoapods.TikiClient\/objc(pl)CLLocationManagerDelegate","doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSObject","doc:\/\/org.cocoapods.TikiClient\/s7CVarArgP","doc:\/\/org.cocoapods.TikiClient\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.TikiClient\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.TikiClient\/SQ","doc:\/\/org.cocoapods.TikiClient\/SH"]}],"abstract":[{"type":"text","text":"Class to manage the location permission"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient"]]},"metadata":{"symbolKind":"class","role":"symbol","title":"LocationDataManager","roleHeading":"Class","modules":[{"name":"TikiClient"}],"navigatorTitle":[{"text":"LocationDataManager","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationDataManager"}],"externalID":"c:@M@TikiClient@objc(cs)LocationDataManager"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LocationDataManager","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/locationManager(_:didFailWithError:)":{"kind":"symbol","title":"locationManager(_:didFailWithError:)","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/locationdatamanager\/locationmanager(_:didfailwitherror:)","navigatorTitle":[{"kind":"identifier","text":"locationManager:didFailWithError:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didFailWithError:)","abstract":[]},"doc://org.cocoapods.TikiClient/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/locationManager":{"kind":"symbol","title":"locationManager","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/locationdatamanager\/locationmanager","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager","abstract":[]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/init()":{"role":"symbol","title":"init()","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/init()","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/tikiclient\/locationdatamanager\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.TikiClient/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.TikiClient\/SH"},"doc://org.cocoapods.TikiClient/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.TikiClient\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/locationManager(_:didUpdateLocations:)":{"role":"symbol","title":"locationManager(_:didUpdateLocations:)","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didUpdateLocations:)","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/tikiclient\/locationdatamanager\/locationmanager(_:didupdatelocations:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"text":"(","kind":"text"},{"text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateLocations","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocation","text":"CLLocation"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"locationManager:didUpdateLocations:","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/7Combine16ObservableObjectP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.TikiClient\/7Combine16ObservableObjectP","title":"Combine.ObservableObject"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/ObservableObject-Implementations":{"abstract":[],"title":"ObservableObject Implementations","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/ObservableObject-Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/tikiclient\/locationdatamanager\/observableobject-implementations","type":"topic"},"doc://org.cocoapods.TikiClient/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.TikiClient\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.TikiClient/objc(pl)CLLocationManagerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(pl)CLLocationManagerDelegate","title":"CLLocationManagerDelegate"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationDataManager"}],"kind":"symbol","title":"LocationDataManager","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager","url":"\/documentation\/tikiclient\/locationdatamanager","type":"topic","abstract":[{"text":"Class to manage the location permission","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"LocationDataManager","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/authorizationStatus":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"authorizationStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLAuthorizationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@CLAuthorizationStatus"},{"kind":"text","text":"?"}],"abstract":[],"title":"authorizationStatus","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/authorizationStatus","kind":"symbol","role":"symbol","url":"\/documentation\/tikiclient\/locationdatamanager\/authorizationstatus","type":"topic"},"doc://org.cocoapods.TikiClient/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.TikiClient\/SQ"},"doc://org.cocoapods.TikiClient/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.TikiClient\/s23CustomStringConvertibleP"},"doc://org.cocoapods.TikiClient/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.TikiClient\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/locationManagerDidChangeAuthorization(_:)":{"kind":"symbol","title":"locationManagerDidChangeAuthorization(_:)","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/locationdatamanager\/locationmanagerdidchangeauthorization(_:)","navigatorTitle":[{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationManagerDidChangeAuthorization"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManagerDidChangeAuthorization(_:)","abstract":[{"text":"Request location permission","type":"text"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","title":"TikiClient","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/tikiclient","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"LocationDataManager","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"LocationDataManager","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"LocationDataManager"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/init()","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didFailWithError:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didUpdateLocations:)","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManagerDidChangeAuthorization(_:)"]}]},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.TikiClient\/objc(pl)CLLocationManagerDelegate"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationDataManager"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManager(_:didFailWithError:)\/title","value":"locationManager:didFailWithError:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManager(_:didFailWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"locationManager:didFailWithError:","kind":"identifier"}]},{"value":"init","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1init()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManager(_:didUpdateLocations:)\/title","value":"locationManager:didUpdateLocations:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}],"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManager(_:didUpdateLocations:)\/fragments"},{"value":"LocationDataManager","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/title","op":"replace"},{"value":[{"text":"LocationDataManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManagerDidChangeAuthorization(_:)\/title","value":"locationManagerDidChangeAuthorization:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"locationManagerDidChangeAuthorization:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManagerDidChangeAuthorization(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}