{"kind":"symbol","metadata":{"title":"TikiClient","modules":[{"name":"TikiClient"}],"externalID":"TikiClient","symbolKind":"module","roleHeading":"Framework","role":"collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient"},"hierarchy":{"paths":[[]]},"variants":[{"paths":["\/documentation\/tikiclient"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tikiclient"]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AccountService","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthService","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureService","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CriptoUtils","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Email","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailRepository","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailService","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/KeyRepository","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/KeyService","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/License","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/TikiClient","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Tracking","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Usecase"],"title":"Classes"},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Account","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthAddrRequest","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthEmailTokenResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthToken","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthTokenResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Config","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailAuthTokenResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailListResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailOauthRefeshTokenResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailOauthResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LicenseRequest","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/MessageHeaderResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/MessagePartBodyResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/MessagePartResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/MessageResponse","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Sender","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Use"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AccountProvider","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AccountStatus","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AccountType","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailProviderEnum","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Permission","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/UsecaseCommon"]},{"identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Swift"],"title":"Extended Modules"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.TikiClient/documentation/TikiClient/TikiClient":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/TikiClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TikiClient"}],"url":"\/documentation\/tikiclient\/tikiclient","kind":"symbol","title":"TikiClient","type":"topic","abstract":[{"text":"Tiki Client Library","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TikiClient"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/MessageHeaderResponse":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/MessageHeaderResponse","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageHeaderResponse"}],"title":"MessageHeaderResponse","abstract":[],"navigatorTitle":[{"text":"MessageHeaderResponse","kind":"identifier"}],"type":"topic","url":"\/documentation\/tikiclient\/messageheaderresponse"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/Use":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/tikiclient\/use","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Use","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Use","kind":"identifier"}],"navigatorTitle":[{"text":"Use","kind":"identifier"}],"abstract":[{"text":"License use.","type":"text"}],"title":"Use"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/EmailListResponse":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailListResponse","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"EmailListResponse","kind":"identifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EmailListResponse"}],"title":"EmailListResponse","role":"symbol","type":"topic","url":"\/documentation\/tikiclient\/emaillistresponse"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/EmailProviderEnum":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/tikiclient\/emailproviderenum","title":"EmailProviderEnum","navigatorTitle":[{"kind":"identifier","text":"EmailProviderEnum"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmailProviderEnum"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailProviderEnum","abstract":[{"text":"Enum representing email providers.","type":"text"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/UsecaseCommon":{"abstract":[{"type":"text","text":"An enumeration of default accepted use cases for a "},{"type":"codeVoice","code":"Usecase"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","title":"UsecaseCommon","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UsecaseCommon","kind":"identifier"}],"navigatorTitle":[{"text":"UsecaseCommon","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/UsecaseCommon","url":"\/documentation\/tikiclient\/usecasecommon","role":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CryptoExportImportManager":{"abstract":[{"text":"This class exists due to the easy and intuitive way of using public keys generated outside iOS in","type":"text"},{"type":"text","text":" "},{"text":"the Security framework and CommonCrypto tools (yes, I’m being sarcastic here).","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"CryptoCertificateImportManager is in charge of importing a certificate and obtaining a valid key"},{"text":" ","type":"text"},{"text":"reference to use in any of SecKey operations (SecKeyEncrypt, SecKeyRawVerify…).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"As far as I know, any other way of importing and using public keys from the outside is not"},{"type":"text","text":" "},{"type":"text","text":"advised: https:\/\/devforums.apple.com\/message\/301532#301532"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager","title":"CryptoExportImportManager","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CryptoExportImportManager"}],"type":"topic","url":"\/documentation\/tikiclient\/cryptoexportimportmanager","navigatorTitle":[{"kind":"identifier","text":"CryptoExportImportManager"}],"role":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"role":"collection","abstract":[],"url":"\/documentation\/tikiclient","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","title":"TikiClient","kind":"symbol","type":"topic"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/Swift":{"url":"\/documentation\/tikiclient\/swift","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Swift","kind":"symbol","title":"Swift"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/TikiClientVersionString":{"url":"\/documentation\/tikiclient\/tikiclientversionstring","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/TikiClientVersionString","kind":"symbol","title":"TikiClientVersionString","fragments":[{"text":"TikiClientVersionString","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/AuthEmailTokenResponse":{"navigatorTitle":[{"kind":"identifier","text":"AuthEmailTokenResponse"}],"kind":"symbol","title":"AuthEmailTokenResponse","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthEmailTokenResponse","url":"\/documentation\/tikiclient\/authemailtokenresponse","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"AuthEmailTokenResponse","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/AuthToken":{"url":"\/documentation\/tikiclient\/authtoken","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthToken"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthToken","navigatorTitle":[{"text":"AuthToken","kind":"identifier"}],"abstract":[],"title":"AuthToken","kind":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/TikiClientVersionNumber":{"fragments":[{"text":"TikiClientVersionNumber","kind":"identifier"}],"title":"TikiClientVersionNumber","type":"topic","url":"\/documentation\/tikiclient\/tikiclientversionnumber","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/TikiClientVersionNumber","kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/Tracking":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Tracking"}],"abstract":[{"text":"Class to manage the advertising tracking","type":"text"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Tracking","title":"Tracking","role":"symbol","navigatorTitle":[{"text":"Tracking","kind":"identifier"}],"url":"\/documentation\/tikiclient\/tracking","type":"topic","kind":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/Config":{"abstract":[],"kind":"symbol","role":"symbol","title":"Config","navigatorTitle":[{"kind":"identifier","text":"Config"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Config"}],"url":"\/documentation\/tikiclient\/config","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Config","type":"topic"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/MessagePartBodyResponse":{"type":"topic","abstract":[],"url":"\/documentation\/tikiclient\/messagepartbodyresponse","role":"symbol","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/MessagePartBodyResponse","navigatorTitle":[{"kind":"identifier","text":"MessagePartBodyResponse"}],"title":"MessagePartBodyResponse","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagePartBodyResponse","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/KeyService":{"type":"topic","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/KeyService","abstract":[{"type":"text","text":"Class to manage the keychain service"}],"kind":"symbol","url":"\/documentation\/tikiclient\/keyservice","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyService"}],"title":"KeyService","navigatorTitle":[{"kind":"identifier","text":"KeyService"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/AuthAddrRequest":{"abstract":[],"type":"topic","url":"\/documentation\/tikiclient\/authaddrrequest","role":"symbol","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthAddrRequest","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthAddrRequest","kind":"identifier"}],"kind":"symbol","title":"AuthAddrRequest","navigatorTitle":[{"text":"AuthAddrRequest","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/EmailAuthTokenResponse":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailAuthTokenResponse","type":"topic","navigatorTitle":[{"text":"EmailAuthTokenResponse","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmailAuthTokenResponse"}],"abstract":[],"url":"\/documentation\/tikiclient\/emailauthtokenresponse","title":"EmailAuthTokenResponse","role":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/KeyRepository":{"url":"\/documentation\/tikiclient\/keyrepository","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Class to manage the keychain"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/KeyRepository","kind":"symbol","title":"KeyRepository","navigatorTitle":[{"kind":"identifier","text":"KeyRepository"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"KeyRepository","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CriptoUtils":{"url":"\/documentation\/tikiclient\/criptoutils","type":"topic","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CriptoUtils","navigatorTitle":[{"kind":"identifier","text":"CriptoUtils"}],"role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CriptoUtils","kind":"identifier"}],"kind":"symbol","title":"CriptoUtils"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/Email":{"url":"\/documentation\/tikiclient\/email","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Email","kind":"symbol","title":"Email","navigatorTitle":[{"kind":"identifier","text":"Email"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Email"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan":{"type":"topic","url":"\/documentation\/tikiclient\/capturescan","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureScan","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan","role":"symbol","title":"CaptureScan","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CaptureScan"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureService":{"url":"\/documentation\/tikiclient\/captureservice","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureService","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Service for capturing and processing receipt data."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CaptureService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureService"}],"title":"CaptureService"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/AccountStatus":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AccountStatus","kind":"symbol","title":"AccountStatus","type":"topic","abstract":[],"url":"\/documentation\/tikiclient\/accountstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AccountStatus","kind":"identifier"}],"navigatorTitle":[{"text":"AccountStatus","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/License":{"title":"License","abstract":[{"text":"Service for managing user licenses.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/License","role":"symbol","url":"\/documentation\/tikiclient\/license","kind":"symbol","navigatorTitle":[{"text":"License","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"License"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/AccountType":{"url":"\/documentation\/tikiclient\/accounttype","abstract":[{"text":"An enumeration representing different types of user accounts.","type":"text"}],"type":"topic","title":"AccountType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccountType"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AccountType","role":"symbol","navigatorTitle":[{"text":"AccountType","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/EmailRepository":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"EmailRepository","kind":"identifier"}],"url":"\/documentation\/tikiclient\/emailrepository","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailRepository"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailRepository","title":"EmailRepository"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/MessageResponse":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/MessageResponse","navigatorTitle":[{"text":"MessageResponse","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"MessageResponse","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MessageResponse","kind":"identifier"}],"url":"\/documentation\/tikiclient\/messageresponse"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/Usecase":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/tikiclient\/usecase","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Usecase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usecase","kind":"identifier"}],"navigatorTitle":[{"text":"Usecase","kind":"identifier"}],"abstract":[{"text":"A use case for a license, describing how an asset may be used.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use cases explicitly define how an asset may be used. Use either our list of common enumerations or define your"},{"type":"text","text":" "},{"text":"own using ","type":"text"},{"type":"codeVoice","code":"UsecaseCommon"},{"text":". Custom use cases can be created by using a value that does not match any of the predefined cases.","type":"text"}],"title":"Usecase"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/AccountProvider":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccountProvider"}],"url":"\/documentation\/tikiclient\/accountprovider","kind":"symbol","title":"AccountProvider","type":"topic","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AccountProvider","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccountProvider"}],"abstract":[]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager","title":"LocationDataManager","abstract":[{"type":"text","text":"Class to manage the location permission"}],"url":"\/documentation\/tikiclient\/locationdatamanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationDataManager"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"LocationDataManager","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/AuthTokenResponse":{"kind":"symbol","title":"AuthTokenResponse","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthTokenResponse"}],"navigatorTitle":[{"kind":"identifier","text":"AuthTokenResponse"}],"abstract":[],"type":"topic","url":"\/documentation\/tikiclient\/authtokenresponse","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthTokenResponse"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/EmailOauthRefeshTokenResponse":{"url":"\/documentation\/tikiclient\/emailoauthrefeshtokenresponse","navigatorTitle":[{"kind":"identifier","text":"EmailOauthRefeshTokenResponse"}],"role":"symbol","type":"topic","kind":"symbol","title":"EmailOauthRefeshTokenResponse","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmailOauthRefeshTokenResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailOauthRefeshTokenResponse"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/Sender":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/sender","navigatorTitle":[{"text":"Sender","kind":"identifier"}],"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Sender"}],"title":"Sender","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Sender"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/AuthService":{"title":"AuthService","abstract":[{"type":"text","text":"Authentication Service for TIKI"}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AuthService","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthService"}],"kind":"symbol","url":"\/documentation\/tikiclient\/authservice","type":"topic","role":"symbol","navigatorTitle":[{"text":"AuthService","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/EmailOauthResponse":{"navigatorTitle":[{"kind":"identifier","text":"EmailOauthResponse"}],"title":"EmailOauthResponse","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailOauthResponse","url":"\/documentation\/tikiclient\/emailoauthresponse","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmailOauthResponse","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/EmailService":{"role":"symbol","abstract":[{"type":"text","text":"Service for managing email accounts."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EmailService","kind":"identifier"}],"url":"\/documentation\/tikiclient\/emailservice","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/EmailService","title":"EmailService","navigatorTitle":[{"text":"EmailService","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/MessagePartResponse":{"navigatorTitle":[{"kind":"identifier","text":"MessagePartResponse"}],"kind":"symbol","title":"MessagePartResponse","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/MessagePartResponse","url":"\/documentation\/tikiclient\/messagepartresponse","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagePartResponse","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient/Account":{"navigatorTitle":[{"text":"Account","kind":"identifier"}],"title":"Account","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/tikiclient\/account","abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Account"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LicenseRequest":{"url":"\/documentation\/tikiclient\/licenserequest","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LicenseRequest","kind":"symbol","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LicenseRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LicenseRequest"}],"title":"LicenseRequest"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/Permission":{"url":"\/documentation\/tikiclient\/permission","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/Permission","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Enumation of iOS permissions and its authorization methods.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Permission","kind":"identifier"}],"navigatorTitle":[{"text":"Permission","kind":"identifier"}],"title":"Permission"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/AccountService":{"url":"\/documentation\/tikiclient\/accountservice","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AccountService"},{"type":"text","text":" class manages user accounts, providing methods for retrieving account"},{"type":"text","text":" "},{"type":"text","text":"information, handling logins, and managing sessions."}],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/AccountService","kind":"symbol","title":"AccountService","navigatorTitle":[{"text":"AccountService","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccountService"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CryptoExportImportManager","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager"]},{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/TikiClientVersionNumber","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/TikiClientVersionString"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":"CryptoExportImportManager","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CryptoExportImportManager\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CryptoExportImportManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"CryptoExportImportManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan\/title","value":"CaptureScan"},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan\/fragments","value":[{"kind":"identifier","text":"CaptureScan"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/title","value":"LocationDataManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/fragments","value":[{"text":"LocationDataManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}