{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/init()","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager"]]},"metadata":{"role":"symbol","externalID":"c:@M@TikiClient@objc(cs)LocationDataManager(im)init","symbolKind":"init","modules":[{"name":"TikiClient"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}]},"variants":[{"paths":["\/documentation\/tikiclient\/locationdatamanager\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tikiclient\/locationdatamanager\/init()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationDataManager"}],"kind":"symbol","title":"LocationDataManager","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager","url":"\/documentation\/tikiclient\/locationdatamanager","type":"topic","abstract":[{"text":"Class to manage the location permission","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"LocationDataManager","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","title":"TikiClient","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/tikiclient","type":"topic"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/init()":{"role":"symbol","title":"init()","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/init()","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/tikiclient\/locationdatamanager\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/title","op":"replace","value":"LocationDataManager"},{"value":[{"text":"LocationDataManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/fragments"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1init()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}