{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tikiclient\/locationdatamanager\/locationmanager(_:didupdatelocations:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tikiclient\/locationdatamanager\/locationmanager(_:didupdatelocations:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didUpdateLocations:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CLLocationManagerDelegate.locationManager(_:didUpdateLocations:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"title":"locationManager(_:didUpdateLocations:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TikiClient@objc(cs)LocationDataManager(im)locationManager:didUpdateLocations:","modules":[{"name":"TikiClient"}],"navigatorTitle":[{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager"]]},"references":{"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager":{"role":"symbol","title":"LocationDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationDataManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationDataManager"}],"url":"\/documentation\/tikiclient\/locationdatamanager"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/locationManager(_:didUpdateLocations:)":{"role":"symbol","title":"locationManager(_:didUpdateLocations:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didUpdateLocations:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManager:didUpdateLocations:"}],"url":"\/documentation\/tikiclient\/locationdatamanager\/locationmanager(_:didupdatelocations:)"},"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"role":"collection","title":"TikiClient","abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","kind":"symbol","type":"topic","url":"\/documentation\/tikiclient"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"locationManager:didUpdateLocations:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"locationManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"manager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateLocations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<CLLocation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locations"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/title","value":"LocationDataManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/fragments","value":[{"kind":"identifier","text":"LocationDataManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManager(_:didUpdateLocations:)\/title","value":"locationManager:didUpdateLocations:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManager(_:didUpdateLocations:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}