{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didFailWithError:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"locationManager(_:didFailWithError:)","role":"symbol","navigatorTitle":[{"text":"locationManager:didFailWithError:","kind":"identifier"}],"modules":[{"name":"TikiClient"}],"roleHeading":"Instance Method","externalID":"c:@M@TikiClient@objc(cs)LocationDataManager(im)locationManager:didFailWithError:","symbolKind":"method"},"kind":"symbol","sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CLLocationManagerDelegate.locationManager(_:didFailWithError:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"locationManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailWithError"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/tikiclient\/locationdatamanager\/locationmanager(_:didfailwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tikiclient\/locationdatamanager\/locationmanager(_:didfailwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/locationManager(_:didFailWithError:)":{"url":"\/documentation\/tikiclient\/locationdatamanager\/locationmanager(_:didfailwitherror:)","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManager(_:didFailWithError:)","kind":"symbol","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"locationManager:didFailWithError:"}],"title":"locationManager(_:didFailWithError:)"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager","title":"LocationDataManager","abstract":[{"type":"text","text":"Class to manage the location permission"}],"url":"\/documentation\/tikiclient\/locationdatamanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationDataManager"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"LocationDataManager","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"role":"collection","abstract":[],"url":"\/documentation\/tikiclient","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","title":"TikiClient","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"locationManager:didFailWithError:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"locationManager:didFailWithError:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"locationManager:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CLLocationManager","kind":"typeIdentifier","text":"CLLocationManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFailWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManager(_:didFailWithError:)\/title","value":"locationManager:didFailWithError:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"locationManager:didFailWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManager(_:didFailWithError:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/title","value":"LocationDataManager"},{"value":[{"kind":"identifier","text":"LocationDataManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/fragments"}]}]}