{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManagerDidChangeAuthorization(_:)"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationManagerDidChangeAuthorization"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager"},{"text":")","kind":"text"}],"title":"locationManagerDidChangeAuthorization(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"}],"modules":[{"name":"TikiClient"}],"roleHeading":"Instance Method","externalID":"c:@M@TikiClient@objc(cs)LocationDataManager(im)locationManagerDidChangeAuthorization:","symbolKind":"method"},"sections":[],"abstract":[{"text":"Request location permission","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationManagerDidChangeAuthorization"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"manager","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocationManager","kind":"typeIdentifier","text":"CLLocationManager"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/tikiclient\/locationdatamanager\/locationmanagerdidchangeauthorization(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tikiclient\/locationdatamanager\/locationmanagerdidchangeauthorization(_:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager","title":"LocationDataManager","abstract":[{"type":"text","text":"Class to manage the location permission"}],"url":"\/documentation\/tikiclient\/locationdatamanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationDataManager"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"LocationDataManager","kind":"identifier"}]},"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"role":"collection","abstract":[],"url":"\/documentation\/tikiclient","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","title":"TikiClient","kind":"symbol","type":"topic"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/LocationDataManager/locationManagerDidChangeAuthorization(_:)":{"url":"\/documentation\/tikiclient\/locationdatamanager\/locationmanagerdidchangeauthorization(_:)","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/LocationDataManager\/locationManagerDidChangeAuthorization(_:)","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Request location permission","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationManagerDidChangeAuthorization","kind":"identifier"},{"kind":"text","text":"("},{"text":"CLLocationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"locationManagerDidChangeAuthorization:","kind":"identifier"}],"title":"locationManagerDidChangeAuthorization(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"locationManagerDidChangeAuthorization:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"locationManagerDidChangeAuthorization:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CLLocationManager","kind":"typeIdentifier","text":"CLLocationManager"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manager"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/title","value":"LocationDataManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager\/fragments","value":[{"text":"LocationDataManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManagerDidChangeAuthorization(_:)\/title","value":"locationManagerDidChangeAuthorization:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1LocationDataManager~1locationManagerDidChangeAuthorization(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"locationManagerDidChangeAuthorization:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}