{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"info"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"InfoKey","preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tikiclient\/capturescan\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tikiclient\/capturescan\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerController(_:didFinishPickingMediaWithInfo:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIImagePickerControllerDelegate.imagePickerController(_:didFinishPickingMediaWithInfo:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"InfoKey","preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TikiClient@objc(cs)CaptureScan(im)imagePickerController:didFinishPickingMediaWithInfo:","modules":[{"name":"TikiClient"}],"navigatorTitle":[{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan"]]},"references":{"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"role":"collection","title":"TikiClient","abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","kind":"symbol","type":"topic","url":"\/documentation\/tikiclient"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan/imagePickerController(_:didFinishPickingMediaWithInfo:)":{"role":"symbol","title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"InfoKey","preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerController(_:didFinishPickingMediaWithInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"url":"\/documentation\/tikiclient\/capturescan\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan":{"role":"symbol","title":"CaptureScan","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureScan"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CaptureScan"}],"url":"\/documentation\/tikiclient\/capturescan"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"imagePickerController:didFinishPickingMediaWithInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"imagePickerController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishPickingMediaWithInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/title","value":"imagePickerController:didFinishPickingMediaWithInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan\/title","value":"CaptureScan"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan\/fragments","value":[{"kind":"identifier","text":"CaptureScan"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}