{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIImagePickerControllerDelegate.imagePickerControllerDidCancel(_:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan"]]},"metadata":{"modules":[{"name":"TikiClient"}],"role":"symbol","title":"imagePickerControllerDidCancel(_:)","externalID":"c:@M@TikiClient@objc(cs)CaptureScan(im)imagePickerControllerDidCancel:","navigatorTitle":[{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imagePickerControllerDidCancel","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController","text":"UIImagePickerController"},{"text":")","kind":"text"}],"symbolKind":"method"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerControllerDidCancel(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePickerControllerDidCancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"text":"UIImagePickerController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tikiclient\/capturescan\/imagepickercontrollerdidcancel(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tikiclient\/capturescan\/imagepickercontrollerdidcancel(_:)"]}],"sections":[],"references":{"doc://org.cocoapods.TikiClient/documentation/TikiClient":{"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient","title":"TikiClient","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/tikiclient","type":"topic"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan":{"kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureScan"}],"type":"topic","navigatorTitle":[{"text":"CaptureScan","kind":"identifier"}],"role":"symbol","title":"CaptureScan","url":"\/documentation\/tikiclient\/capturescan","identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan"},"doc://org.cocoapods.TikiClient/documentation/TikiClient/CaptureScan/imagePickerControllerDidCancel(_:)":{"role":"symbol","navigatorTitle":[{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"title":"imagePickerControllerDidCancel(_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerControllerDidCancel"},{"kind":"text","text":"("},{"text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/tikiclient\/capturescan\/imagepickercontrollerdidcancel(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.TikiClient\/documentation\/TikiClient\/CaptureScan\/imagePickerControllerDidCancel(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"imagePickerControllerDidCancel:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"imagePickerControllerDidCancel:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":" *) ","kind":"text"},{"text":"_","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"CaptureScan","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan\/fragments","value":[{"text":"CaptureScan","kind":"identifier"}]},{"value":"imagePickerControllerDidCancel:","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan~1imagePickerControllerDidCancel(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imagePickerControllerDidCancel:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TikiClient~1documentation~1TikiClient~1CaptureScan~1imagePickerControllerDidCancel(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}